site_name: "Harshin Kamal Asok"
site_description: "Research Website"
repo_url: "https://github.com/hkasok/hkasok.github.io"
repo_name: "GitHub"
docs_dir: "docs/"
site_dir: "_site_mkdocs/"
theme:
  name: "readthedocs"
  features:
    - navigation.tabs
    - navigation.sections
prev_next_buttons_location: "none"
copyright: "Â© 2025 Harshin Kamal Asok"

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Contact: contact.md

