site_name: "Harshin Kamal Asok"
site_description: "Personal Research Website of Harshin Kamal Asok"
repo_url: "https://github.com/hkasok/hkasok.github.io"
repo_name: "GitHub"
docs_dir: "docs/"
site_dir: "site/"
theme:
  name: "readthedocs"
  highlightjs: true

nav:
  - Home: index.md
  - Research: research.md
  - Publications: publications.md
  - Softwares: softwares.md
  - Contact: contact.md

copyright: "Â© 2025 Harshin Kamal Asok"

